# Automatically generated by pb2py
# fmt: off
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

BLOB: Literal[0] = 0
TUPLE: Literal[1] = 1
